name: AssaultPlugin
description: Plugin of assault with SaberFactions 
main: fr.Boulldogo.AssaultPlugin.Main 
version: 1.0
depends: [SaberFactions]
commands:
  assault:
    description: Main command of the assault plugin