name: AssaultPlugin
description: Plugin of assault with SaberFactions 
main: fr.Boulldogo.AssaultPlugin.AssaultPlugin
version: 1.3.4
depend: [Factions]
api-version: 1.13
commands:
  assault:
    description: Main command of assault plugin